name: Bug Report (with form)
description: Report an issue related to Jmix framework.
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Description
      description: A description of what the bug is.
      placeholder: "Screen BBB from the AAA add-on cannot be opened."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: "Example:\n1. Add the AAA add-on to the project.\n2. Run the application\n3. Open the BBB view."
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Provide a description of what actually happens. If there is an error message in the application log, please provide the full stacktrace.
      placeholder: "Example: BBB view is not opened and there is an exception in the log."
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: "Example: BBB view is opened."
    validations:
      required: true
  - type: textarea
    id: sample-project
    attributes:
      label: Sample Project
      description: "Attach a zip-archive with a sample project or provide a link to a GitHub repository with a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Jmix Studio Toolbar provides an [action](https://docs.jmix.io/jmix/studio/tool-window.html#gradle) for creating a zip-archive from your project. Reports that include a sample will take priority over reports that do not."
      placeholder: "Example: https://githib.com/someuser/some-project"
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment in which the issue reproduces.
      value: "Jmix version: \nJava version: \nOS: \nBrowser: "
    validations:
      required: true
